### ISSUE TITLE
Auto-detection feature does not work (is not implemented?)

### ISSUE THREAD

**Issue by jacobq** [dfcreative/gaussian-fit#1]
The [`README.md` has this comment about `how.components`](https://github.com/dfcreative/gaussian-fit#usage): 
> if null - the components will be detected automatically

However, the example code returns an empty array, and the [source for `fit`](https://github.com/dfcreative/gaussian-fit/blob/aa3d05ac01402c5b64f414dc2607dccf5d4383c8/index.js#L65-L76) appears to have some placeholder comments but no implementation.

If this is correct then it would be nice to add a note to the README saying that that feature is not yet implemented.

**Comment by dy** [comment]
Yes, it is to be implemented. Thank you for notion.

**Comment by jacobq** [comment]
Closing since README now includes `TODO` in comment next to unimplemented stuff.
